# Generated by Django 4.0.3 on 2022-05-02 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trenhelp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='trenhelp.training'),
        ),
    ]
