# Generated by Django 3.2.5 on 2022-05-08 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trenhelp', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='trenhelp.profile'),
        ),
    ]
