# Generated by Django 3.2.5 on 2022-05-08 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trenhelp', '0005_training_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='profile',
        ),
        migrations.AddField(
            model_name='training',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL),
        ),
    ]
